SESSION_UNMANAGED = "unmanaged"
SESSION_NEW = "new"
SESSION_FETCHING = "fetching"
SESSION_FETCHED = "fetched"
SESSION_PROCESSING = "processing"
SESSION_PROCESSED = "processed"
SESSION_SYNCING = "syncing"
SESSION_SYNCED = "synced"
SESSION_CHANGED = "changed"
SESSION_REMOVED = "removed"
SESSION_DELETED = "deleted"
SESSION_FAILED = "failed"
SESSION_SKIPPED = "skipped"

FILE_UNHARVESTED = "unharvested"
FILE_NEW = "new"
FILE_FETCHING = "fetching"
FILE_FETCHED = "fetched"
FILE_PROCESSING = "processing"
FILE_PROCESSED = "processed"
FILE_SYNCING = "syncing"
FILE_SYNCED = "synced"
FILE_CHANGED = "changed"
FILE_REMOVED = "removed"
FILE_DELETING = "deleting"
FILE_DELETED = "deleted"
FILE_INVALID = "invalid"
FILE_FAILED = "failed"

ARCHIVE_UNSYNCED = "unsynced"
ARCHIVE_SYNCING = "syncing"
ARCHIVE_SYNCED = "synced"

LOG_STATUS = "status"
LOG_WARNING = "warning"
LOG_ERROR = "error"
